<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Markdig" Version="0.37.0" />
        <PackageReference Include="Telerik.UI.for.Blazor" Version="14.1.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Ben.Data.Common\Ben.Data.Common.csproj" />
        <ProjectReference Include="..\Ben.Service.Models\Ben.Service.Models.csproj" />
        <ProjectReference Include="..\Ben.Web.Services\Ben.Web.Services.csproj" />
        <ProjectReference Include="../Ben.Video.Editor/Ben.Video.Editor.csproj" />
    </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ben.Web.Tests" />
  </ItemGroup>

</Project>
