namespace Ben.Data.Source.Entities
{
    /// <summary>
    /// One record of a native sidecar being installed, or of a browser pairing with one.
    /// </summary>
    /// <remarks>
    /// <para>The sidecar runs on the user's own machine and the site never otherwise hears from it,
    /// so without this there is no way to answer "who is running it, on what, and which version" —
    /// which matters most when deciding whether an old build is still out there before changing the
    /// protocol.</para>
    ///
    /// <para>Deliberately not an <c>IAuditableEntity</c>: the install ping arrives before anyone has
    /// signed in, so there is no <c>CreatedByAppUserId</c> to record. <see cref="AppUserId"/> is
    /// null for exactly that case and set when a signed-in browser pairs.</para>
    ///
    /// <para><see cref="IpAddress"/> is taken from the connection server-side, never from the
    /// request body — a client-supplied address is worth nothing.</para>
    /// </remarks>
    public class SidecarInstallLog
    {
        public Guid Id { get; set; }

        /// <summary>
        /// Identifies one installation across its lifetime, generated by the sidecar and stable
        /// across restarts. Lets an install and the pairings that follow it be tied together
        /// without needing an account at install time.
        /// </summary>
        public Guid InstallId { get; set; }

        /// <summary><c>Install</c> or <c>Pair</c> — see <c>SidecarTelemetryEventTypes</c>.</summary>
        public string EventType { get; set; } = null!;

        /// <summary>Sidecar assembly version, e.g. "1.0.0.0".</summary>
        public string? Version { get; set; }

        /// <summary>Runtime identifier the sidecar was built for, e.g. "osx-arm64".</summary>
        public string? Platform { get; set; }

        /// <summary>Set when a signed-in browser pairs; null for the anonymous install ping.</summary>
        public Guid? AppUserId { get; set; }

        /// <summary>Remote address of the caller, resolved server-side.</summary>
        public string? IpAddress { get; set; }

        public DateTime DateCreated { get; set; }

        public virtual AppUser? AppUser { get; set; }
    }
}
