using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Ben.Data.Source.Migrations
{
    /// <summary>
    /// Rewrites every stored Bootstrap Icons class (<c>bi bi-*</c>) as its Font Awesome
    /// equivalent, and gives bare <c>fa-*</c> values the style class they were missing.
    /// </summary>
    /// <remarks>
    /// <para><b>Ben's decision, 2026-09-27:</b> "Use font awesome." The site never loaded the
    /// Bootstrap Icons font, so every lookup type seeded with a <c>bi bi-*</c> class, and every icon
    /// picked from the picker's Bootstrap tab, rendered as nothing. Font Awesome Pro is loaded
    /// sitewide, so the stored values move to it rather than a second icon font being added.</para>
    ///
    /// <para><b>The map covers every name anything here could have written:</b> the picker's
    /// whole Bootstrap list plus the seeders' values. A value typed into an Icon Class box by hand
    /// that is not in it is left alone. Targets are Font Awesome 7 canonical names, all checked
    /// against the 7.3.1 metadata for a solid style (<c>fas</c>); the five brand-only ones
    /// (PayPal, Twitch, Twitter, USB, YouTube) are written as <c>fab</c>.</para>
    ///
    /// <para><b>Bare <c>fa-*</c> values</b> (the seeded message types: <c>fa-life-ring</c> and
    /// four others) have no style class, and Font Awesome draws nothing without one, so they get
    /// <c>fas</c> in front. Only single-class values: <c>fa-solid fa-ghost</c> already has one.</para>
    ///
    /// <para><b>Down does not restore the old values.</b> Several Bootstrap names map to one
    /// Font Awesome name, so the originals are not recoverable, and they drew nothing anyway.</para>
    /// </remarks>
    public partial class ConvertBootstrapIconClassesToFontAwesome : Migration
    {
        private static readonly string[] Tables =
        [
            "EquipmentCategories",
            "ExperienceCategories",
            "ExperienceTypes",
            "OrgCalendarEventTypes",
            "OrganizationAddressTypes",
            "OrganizationEmailTypes",
            "OrganizationLinkTypes",
            "OrganizationNoteTypes",
            "OrganizationPhoneTypes",
            "UploadFileTypes",
            "UserAddressTypes",
            "UserEmailTypes",
            "UserLinkTypes",
            "UserMessageTypes",
            "UserNoteTypes",
            "UserPhoneTypes",
        ];

        private static readonly (string Bootstrap, string FontAwesome)[] Map =
        [
            ("alarm", "fas fa-alarm-clock"),
            ("app", "fas fa-square"),
            ("archive", "fas fa-box-archive"),
            ("arrow-bar-down", "fas fa-arrow-down-to-line"),
            ("arrow-bar-left", "fas fa-arrow-left-to-line"),
            ("arrow-bar-right", "fas fa-arrow-right-to-line"),
            ("arrow-bar-up", "fas fa-arrow-up-to-line"),
            ("arrow-clockwise", "fas fa-arrow-rotate-right"),
            ("arrow-counterclockwise", "fas fa-arrow-rotate-left"),
            ("arrow-down", "fas fa-arrow-down"),
            ("arrow-down-circle", "fas fa-circle-arrow-down"),
            ("arrow-down-left", "fas fa-arrow-down-left"),
            ("arrow-down-right", "fas fa-arrow-down-right"),
            ("arrow-left", "fas fa-arrow-left"),
            ("arrow-left-circle", "fas fa-circle-arrow-left"),
            ("arrow-repeat", "fas fa-arrows-rotate"),
            ("arrow-return-left", "fas fa-arrow-turn-down-left"),
            ("arrow-return-right", "fas fa-arrow-turn-down-right"),
            ("arrow-right", "fas fa-arrow-right"),
            ("arrow-right-circle", "fas fa-circle-arrow-right"),
            ("arrow-up", "fas fa-arrow-up"),
            ("arrow-up-circle", "fas fa-circle-arrow-up"),
            ("arrow-up-right", "fas fa-arrow-up-right"),
            ("arrows-move", "fas fa-arrows-up-down-left-right"),
            ("aspect-ratio", "fas fa-rectangle-wide"),
            ("asterisk", "fas fa-asterisk"),
            ("at", "fas fa-at"),
            ("award", "fas fa-award"),
            ("bag", "fas fa-bag-shopping"),
            ("bag-check", "fas fa-bag-shopping"),
            ("bag-dash", "fas fa-bag-shopping"),
            ("bag-fill", "fas fa-bag-shopping"),
            ("bag-plus", "fas fa-bag-shopping-plus"),
            ("bag-x", "fas fa-bag-shopping-minus"),
            ("balloon", "fas fa-balloon"),
            ("balloon-heart", "fas fa-balloon"),
            ("bar-chart", "fas fa-chart-bar"),
            ("bar-chart-fill", "fas fa-chart-bar"),
            ("bar-chart-line", "fas fa-chart-line"),
            ("bar-chart-steps", "fas fa-chart-gantt"),
            ("battery", "fas fa-battery-full"),
            ("battery-charging", "fas fa-battery-bolt"),
            ("battery-full", "fas fa-battery-full"),
            ("battery-half", "fas fa-battery-half"),
            ("bell", "fas fa-bell"),
            ("bell-fill", "fas fa-bell"),
            ("bell-slash", "fas fa-bell-slash"),
            ("bluetooth", "fas fa-bluetooth"),
            ("book", "fas fa-book"),
            ("book-fill", "fas fa-book"),
            ("book-half", "fas fa-book-open"),
            ("bookmark", "fas fa-bookmark"),
            ("bookmark-fill", "fas fa-bookmark"),
            ("bookmarks", "fas fa-bookmark"),
            ("box", "fas fa-box"),
            ("box-arrow-down", "fas fa-box-arrow-down"),
            ("box-arrow-up", "fas fa-box-arrow-up"),
            ("box-seam", "fas fa-box-open"),
            ("briefcase", "fas fa-briefcase"),
            ("brightness-high", "fas fa-sun-bright"),
            ("broadcast", "fas fa-tower-broadcast"),
            ("brush", "fas fa-brush"),
            ("bug", "fas fa-bug"),
            ("building", "fas fa-building"),
            ("building-check", "fas fa-building-circle-check"),
            ("bullseye", "fas fa-bullseye"),
            ("calculator", "fas fa-calculator"),
            ("calendar", "fas fa-calendar"),
            ("calendar-check", "fas fa-calendar-check"),
            ("calendar-event", "fas fa-calendar-day"),
            ("calendar-fill", "fas fa-calendar"),
            ("calendar-range", "fas fa-calendar-range"),
            ("camera", "fas fa-camera"),
            ("camera-fill", "fas fa-camera"),
            ("camera-reels", "fas fa-camera-movie"),
            ("camera-video", "fas fa-video"),
            ("capslock", "fas fa-up"),
            ("card-checklist", "fas fa-list-check"),
            ("card-heading", "fas fa-rectangle-list"),
            ("card-image", "fas fa-image"),
            ("card-list", "fas fa-rectangle-list"),
            ("card-text", "fas fa-memo"),
            ("cart", "fas fa-cart-shopping"),
            ("cart-check", "fas fa-cart-circle-check"),
            ("cart-fill", "fas fa-cart-shopping"),
            ("cart-plus", "fas fa-cart-plus"),
            ("cash", "fas fa-money-bill"),
            ("cash-coin", "fas fa-money-bill-1-wave"),
            ("chat", "fas fa-comment"),
            ("chat-dots", "fas fa-comment-dots"),
            ("chat-dots-fill", "fas fa-comment-dots"),
            ("chat-fill", "fas fa-comment"),
            ("chat-left", "fas fa-message"),
            ("chat-left-text", "fas fa-message-lines"),
            ("chat-right", "fas fa-comment"),
            ("chat-square", "fas fa-message"),
            ("check", "fas fa-check"),
            ("check-circle", "fas fa-circle-check"),
            ("check-circle-fill", "fas fa-circle-check"),
            ("check-lg", "fas fa-check"),
            ("check-square", "fas fa-square-check"),
            ("check2", "fas fa-check"),
            ("check2-all", "fas fa-check-double"),
            ("check2-circle", "fas fa-circle-check"),
            ("check2-square", "fas fa-square-check"),
            ("chevron-down", "fas fa-chevron-down"),
            ("chevron-left", "fas fa-chevron-left"),
            ("chevron-right", "fas fa-chevron-right"),
            ("chevron-up", "fas fa-chevron-up"),
            ("circle", "fas fa-circle"),
            ("clipboard", "fas fa-clipboard"),
            ("clock", "fas fa-clock"),
            ("clock-fill", "fas fa-clock"),
            ("cloud", "fas fa-cloud"),
            ("cloud-arrow-down", "fas fa-cloud-arrow-down"),
            ("cloud-arrow-up", "fas fa-cloud-arrow-up"),
            ("cloud-check", "fas fa-cloud-check"),
            ("cloud-download", "fas fa-cloud-arrow-down"),
            ("cloud-fill", "fas fa-cloud"),
            ("cloud-sun", "fas fa-cloud-sun"),
            ("cloud-upload", "fas fa-cloud-arrow-up"),
            ("code", "fas fa-code"),
            ("code-slash", "fas fa-code"),
            ("code-square", "fas fa-square-code"),
            ("collection", "fas fa-layer-group"),
            ("columns", "fas fa-table-columns"),
            ("columns-gap", "fas fa-columns-3"),
            ("compass", "fas fa-compass"),
            ("compass-fill", "fas fa-compass"),
            ("cone", "fas fa-traffic-cone"),
            ("cone-striped", "fas fa-traffic-cone"),
            ("controller", "fas fa-gamepad"),
            ("copy", "fas fa-copy"),
            ("cpu", "fas fa-microchip"),
            ("crop", "fas fa-crop"),
            ("currency-dollar", "fas fa-dollar-sign"),
            ("currency-euro", "fas fa-euro-sign"),
            ("cursor", "fas fa-arrow-pointer"),
            ("dash", "fas fa-minus"),
            ("dash-circle", "fas fa-circle-minus"),
            ("database", "fas fa-database"),
            ("database-fill", "fas fa-database"),
            ("diagram-3", "fas fa-sitemap"),
            ("display", "fas fa-display"),
            ("door-closed", "fas fa-door-closed"),
            ("door-open", "fas fa-door-open"),
            ("download", "fas fa-download"),
            ("droplet", "fas fa-droplet"),
            ("droplet-fill", "fas fa-droplet"),
            ("ear", "fas fa-ear-listen"),
            ("earbuds", "fas fa-headphones"),
            ("egg", "fas fa-egg"),
            ("emoji-angry", "fas fa-face-angry"),
            ("emoji-expressionless", "fas fa-face-expressionless"),
            ("emoji-heart-eyes", "fas fa-face-grin-hearts"),
            ("emoji-laughing", "fas fa-face-laugh"),
            ("emoji-neutral", "fas fa-face-meh"),
            ("emoji-smile", "fas fa-face-smile"),
            ("emoji-sunglasses", "fas fa-face-sunglasses"),
            ("emoji-wink", "fas fa-face-smile-wink"),
            ("envelope", "fas fa-envelope"),
            ("envelope-fill", "fas fa-envelope"),
            ("envelope-open", "fas fa-envelope-open"),
            ("envelope-plus", "fas fa-envelope-open-text"),
            ("eraser", "fas fa-eraser"),
            ("exclude", "fas fa-object-exclude"),
            ("eye", "fas fa-eye"),
            ("eye-fill", "fas fa-eye"),
            ("eye-slash", "fas fa-eye-slash"),
            ("file", "fas fa-file"),
            ("file-arrow-down", "fas fa-file-arrow-down"),
            ("file-arrow-up", "fas fa-file-arrow-up"),
            ("file-bar-graph", "fas fa-file-chart-column"),
            ("file-check", "fas fa-file-check"),
            ("file-code", "fas fa-file-code"),
            ("file-earmark", "fas fa-file"),
            ("file-earmark-code", "fas fa-file-code"),
            ("file-earmark-image", "fas fa-file-image"),
            ("file-earmark-music", "fas fa-file-music"),
            ("file-earmark-pdf", "fas fa-file-pdf"),
            ("file-earmark-text", "fas fa-file-lines"),
            ("file-earmark-word", "fas fa-file-word"),
            ("file-earmark-zip", "fas fa-file-zipper"),
            ("file-image", "fas fa-file-image"),
            ("file-music", "fas fa-file-music"),
            ("file-pdf", "fas fa-file-pdf"),
            ("file-person", "fas fa-file-user"),
            ("file-play", "fas fa-file-video"),
            ("file-plus", "fas fa-file-plus"),
            ("file-richtext", "fas fa-file-lines"),
            ("file-text", "fas fa-file-lines"),
            ("file-word", "fas fa-file-word"),
            ("file-zip", "fas fa-file-zip"),
            ("files", "fas fa-files"),
            ("film", "fas fa-film"),
            ("filter", "fas fa-filter"),
            ("flag", "fas fa-flag"),
            ("flag-fill", "fas fa-flag"),
            ("folder", "fas fa-folder"),
            ("folder-check", "fas fa-folder-check"),
            ("folder-fill", "fas fa-folder"),
            ("folder-minus", "fas fa-folder-minus"),
            ("folder-open", "fas fa-folder-open"),
            ("folder-plus", "fas fa-folder-plus"),
            ("folder-symlink", "fas fa-folder-arrow-up"),
            ("folder-x", "fas fa-folder-xmark"),
            ("fonts", "fas fa-font"),
            ("forward", "fas fa-forward"),
            ("funnel", "fas fa-filter"),
            ("funnel-fill", "fas fa-filter"),
            ("gear", "fas fa-gear"),
            ("gear-fill", "fas fa-gear"),
            ("gear-wide", "fas fa-gear"),
            ("geo-alt", "fas fa-location-dot"),
            ("geo-fill", "fas fa-location-pin"),
            ("gift", "fas fa-gift"),
            ("gift-fill", "fas fa-gift"),
            ("globe", "fas fa-globe"),
            ("globe-americas", "fas fa-earth-americas"),
            ("globe-europe-africa", "fas fa-earth-europe"),
            ("graph-down", "fas fa-chart-line-down"),
            ("graph-up", "fas fa-chart-line-up"),
            ("grid", "fas fa-grid"),
            ("grid-1x2", "fas fa-grid-2"),
            ("grid-3x2", "fas fa-grid"),
            ("grid-fill", "fas fa-grid"),
            ("hammer", "fas fa-hammer"),
            ("hand-index", "fas fa-hand-point-up"),
            ("hand-thumbs-down", "fas fa-thumbs-down"),
            ("hand-thumbs-up", "fas fa-thumbs-up"),
            ("hash", "fas fa-hashtag"),
            ("headphones", "fas fa-headphones"),
            ("heart", "fas fa-heart"),
            ("heart-fill", "fas fa-heart"),
            ("house", "fas fa-house"),
            ("house-door", "fas fa-house-chimney"),
            ("house-door-fill", "fas fa-house-chimney"),
            ("house-fill", "fas fa-house"),
            ("image", "fas fa-image"),
            ("inbox", "fas fa-inbox"),
            ("info-circle", "fas fa-circle-info"),
            ("info-circle-fill", "fas fa-circle-info"),
            ("input-cursor", "fas fa-i-cursor"),
            ("journal-text", "fas fa-book"),
            ("joystick", "fas fa-joystick"),
            ("kanban", "fas fa-square-kanban"),
            ("key", "fas fa-key"),
            ("keyboard", "fas fa-keyboard"),
            ("ladder", "fas fa-water-ladder"),
            ("laptop", "fas fa-laptop"),
            ("layers", "fas fa-layer-group"),
            ("layout-sidebar", "fas fa-sidebar"),
            ("layout-split", "fas fa-table-columns"),
            ("lightning", "fas fa-bolt"),
            ("lightning-charge", "fas fa-bolt"),
            ("lightning-fill", "fas fa-bolt"),
            ("link", "fas fa-link"),
            ("link-45deg", "fas fa-link"),
            ("list", "fas fa-list"),
            ("list-check", "fas fa-list-check"),
            ("list-ol", "fas fa-list-ol"),
            ("list-ul", "fas fa-list-ul"),
            ("lock", "fas fa-lock"),
            ("lock-fill", "fas fa-lock"),
            ("mailbox", "fas fa-mailbox"),
            ("map", "fas fa-map"),
            ("map-fill", "fas fa-map"),
            ("megaphone", "fas fa-megaphone"),
            ("mic", "fas fa-microphone"),
            ("mic-fill", "fas fa-microphone"),
            ("mic-mute", "fas fa-microphone-slash"),
            ("minecart", "fas fa-cart-flatbed"),
            ("modem", "fas fa-router"),
            ("moon", "fas fa-moon"),
            ("mouse", "fas fa-computer-mouse"),
            ("music-note", "fas fa-music-note"),
            ("music-note-beamed", "fas fa-music"),
            ("music-note-list", "fas fa-list-music"),
            ("newspaper", "fas fa-newspaper"),
            ("node-minus", "fas fa-circle-minus"),
            ("node-plus", "fas fa-circle-plus"),
            ("nurse", "fas fa-user-nurse"),
            ("palette", "fas fa-palette"),
            ("palette-fill", "fas fa-palette"),
            ("paperclip", "fas fa-paperclip"),
            ("patch-check", "fas fa-badge-check"),
            ("patch-plus", "fas fa-badge"),
            ("patch-question", "fas fa-circle-question"),
            ("pause", "fas fa-pause"),
            ("pause-circle", "fas fa-circle-pause"),
            ("paypal", "fab fa-paypal"),
            ("pen", "fas fa-pen"),
            ("pencil", "fas fa-pencil"),
            ("pencil-fill", "fas fa-pencil"),
            ("pencil-square", "fas fa-square-pen"),
            ("people", "fas fa-people"),
            ("people-fill", "fas fa-people"),
            ("person", "fas fa-person"),
            ("person-badge", "fas fa-id-badge"),
            ("person-check", "fas fa-user-check"),
            ("person-circle", "fas fa-circle-user"),
            ("person-dash", "fas fa-user-minus"),
            ("person-fill", "fas fa-person"),
            ("person-gear", "fas fa-user-gear"),
            ("person-lines-fill", "fas fa-address-card"),
            ("person-lock", "fas fa-user-lock"),
            ("person-plus", "fas fa-user-plus"),
            ("person-raised-hand", "fas fa-hand"),
            ("person-vcard", "fas fa-id-card"),
            ("person-workspace", "fas fa-chalkboard-user"),
            ("phone", "fas fa-mobile"),
            ("phone-fill", "fas fa-mobile"),
            ("pie-chart", "fas fa-chart-pie"),
            ("pie-chart-fill", "fas fa-chart-pie"),
            ("pin", "fas fa-thumbtack"),
            ("pin-angle", "fas fa-thumbtack"),
            ("pin-fill", "fas fa-thumbtack"),
            ("play", "fas fa-play"),
            ("play-btn", "fas fa-circle-play"),
            ("play-circle", "fas fa-circle-play"),
            ("play-fill", "fas fa-play"),
            ("plug", "fas fa-plug"),
            ("plus", "fas fa-plus"),
            ("plus-circle", "fas fa-circle-plus"),
            ("plus-circle-fill", "fas fa-circle-plus"),
            ("plus-lg", "fas fa-plus"),
            ("plus-square", "fas fa-square-plus"),
            ("power", "fas fa-power-off"),
            ("printer", "fas fa-print"),
            ("puzzle", "fas fa-puzzle"),
            ("question", "fas fa-question"),
            ("question-circle", "fas fa-circle-question"),
            ("question-circle-fill", "fas fa-circle-question"),
            ("question-lg", "fas fa-question"),
            ("question-octagon", "fas fa-octagon-exclamation"),
            ("quote", "fas fa-quote-left"),
            ("reception-4", "fas fa-signal"),
            ("record", "fas fa-circle-dot"),
            ("recycle", "fas fa-recycle"),
            ("reply", "fas fa-reply"),
            ("robot", "fas fa-robot"),
            ("rocket", "fas fa-rocket"),
            ("rss", "fas fa-rss"),
            ("rss-fill", "fas fa-rss"),
            ("rulers", "fas fa-ruler-combined"),
            ("save", "fas fa-floppy-disk"),
            ("save-fill", "fas fa-floppy-disk"),
            ("scissors", "fas fa-scissors"),
            ("search", "fas fa-magnifying-glass"),
            ("send", "fas fa-paper-plane-top"),
            ("server", "fas fa-server"),
            ("share", "fas fa-share"),
            ("shield", "fas fa-shield"),
            ("shield-check", "fas fa-shield-check"),
            ("shield-fill", "fas fa-shield"),
            ("shop", "fas fa-shop"),
            ("shop-window", "fas fa-shop"),
            ("shuffle", "fas fa-shuffle"),
            ("signal", "fas fa-signal"),
            ("skip-backward", "fas fa-backward"),
            ("skip-forward", "fas fa-forward"),
            ("skip-start", "fas fa-backward-step"),
            ("sliders", "fas fa-sliders"),
            ("sliders2", "fas fa-sliders"),
            ("smartwatch", "fas fa-watch-smart"),
            ("snow", "fas fa-snowflake"),
            ("soundwave", "fas fa-waveform-lines"),
            ("speedometer", "fas fa-gauge"),
            ("speedometer2", "fas fa-gauge-high"),
            ("square", "fas fa-square"),
            ("stack", "fas fa-layer-group"),
            ("star", "fas fa-star"),
            ("star-fill", "fas fa-star"),
            ("star-half", "fas fa-star-half"),
            ("stars", "fas fa-stars"),
            ("sticky", "fas fa-note-sticky"),
            ("stop", "fas fa-stop"),
            ("stop-circle", "fas fa-circle-stop"),
            ("stoplights", "fas fa-traffic-light"),
            ("stopwatch", "fas fa-stopwatch"),
            ("stopwatch-fill", "fas fa-stopwatch"),
            ("suit-club", "fas fa-club"),
            ("suit-diamond", "fas fa-diamond"),
            ("suit-heart", "fas fa-heart"),
            ("suit-spade", "fas fa-spade"),
            ("sunglasses", "fas fa-sunglasses"),
            ("symmetry-horizontal", "fas fa-reflect-horizontal"),
            ("table", "fas fa-table"),
            ("tablet", "fas fa-tablet"),
            ("tag", "fas fa-tag"),
            ("tag-fill", "fas fa-tag"),
            ("tags", "fas fa-tags"),
            ("tags-fill", "fas fa-tags"),
            ("telephone", "fas fa-phone"),
            ("telephone-fill", "fas fa-phone"),
            ("telephone-forward", "fas fa-phone-arrow-right"),
            ("telephone-plus", "fas fa-phone-plus"),
            ("terminal", "fas fa-terminal"),
            ("terminal-fill", "fas fa-terminal"),
            ("text-left", "fas fa-align-left"),
            ("text-right", "fas fa-align-right"),
            ("thermometer", "fas fa-thermometer"),
            ("thermometer-half", "fas fa-temperature-half"),
            ("toggle-off", "fas fa-toggle-off"),
            ("toggle-on", "fas fa-toggle-on"),
            ("toolbox", "fas fa-toolbox"),
            ("tools", "fas fa-screwdriver-wrench"),
            ("translate", "fas fa-language"),
            ("trash", "fas fa-trash"),
            ("trash-fill", "fas fa-trash"),
            ("trash2", "fas fa-trash-can"),
            ("trophy", "fas fa-trophy"),
            ("trophy-fill", "fas fa-trophy"),
            ("truck", "fas fa-truck"),
            ("tv", "fas fa-tv"),
            ("twitch", "fab fa-twitch"),
            ("twitter", "fab fa-twitter"),
            ("type", "fas fa-text"),
            ("upc", "fas fa-barcode"),
            ("upload", "fas fa-upload"),
            ("usb", "fab fa-usb"),
            ("vector-pen", "fas fa-pen-nib"),
            ("vinyl", "fas fa-record-vinyl"),
            ("voicemail", "fas fa-voicemail"),
            ("volume-down", "fas fa-volume-low"),
            ("volume-mute", "fas fa-volume-xmark"),
            ("volume-up", "fas fa-volume-high"),
            ("walkie-talkie", "fas fa-walkie-talkie"),
            ("wallet", "fas fa-wallet"),
            ("watch", "fas fa-watch"),
            ("wifi", "fas fa-wifi"),
            ("window", "fas fa-window"),
            ("wrench", "fas fa-wrench"),
            ("wrench-adjustable", "fas fa-wrench"),
            ("x", "fas fa-xmark"),
            ("x-circle", "fas fa-circle-xmark"),
            ("x-circle-fill", "fas fa-circle-xmark"),
            ("x-lg", "fas fa-xmark"),
            ("x-octagon", "fas fa-octagon-xmark"),
            ("x-square", "fas fa-square-xmark"),
            ("youtube", "fab fa-youtube"),
            ("zoom-in", "fas fa-magnifying-glass-plus"),
            ("zoom-out", "fas fa-magnifying-glass-minus"),
        ];

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var values = string.Join(",\n", Map.Select(m => $"(N'bi bi-{m.Bootstrap}', N'{m.FontAwesome}')"));

            foreach (var table in Tables)
            {
                migrationBuilder.Sql($@"
                    UPDATE t SET [IconClass] = m.[New]
                    FROM [{table}] t
                    JOIN (VALUES
                    {values}
                    ) AS m([Old], [New]) ON t.[IconClass] = m.[Old];");

                migrationBuilder.Sql($@"
                    UPDATE [{table}] SET [IconClass] = N'fas ' + [IconClass]
                    WHERE [IconClass] LIKE N'fa-%' AND CHARINDEX(N' ', [IconClass]) = 0;");
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Not reversible: see the remarks.
        }
    }
}
