// <auto-generated />
using System;
using Ben.Data.Source.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ben.Data.Source.Migrations
{
    [DbContext(typeof(BenDataContext))]
    [Migration("20260709155716_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ben.Data.Source.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrlName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrganizationAddressTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("OrganizationAddressTypeId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("OrganizationAddresses");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationAddressType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("OrganizationAddressTypes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationEmailTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidationToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("OrganizationEmailTypeId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("OrganizationEmails");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationEmailType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("OrganizationEmailTypes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateVerifiedApproved")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerifiedApproved")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationLinkTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VerifiedApprovedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationLinkTypeId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.HasIndex("VerifiedApprovedByAppUserId");

                    b.ToTable("OrganizationLinks");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationLinkType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("OrganizationLinkTypes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ItemRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoteBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteSubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationNoteTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentNoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationNoteTypeId");

                    b.HasIndex("ParentNoteId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("OrganizationNotes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationNoteType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("OrganizationNoteTypes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHome")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PageHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrlName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("OrganizationPages");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCellular")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationPhoneTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidationToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationPhoneTypeId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("OrganizationPhones");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationPhoneType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("OrganizationPhoneTypes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserAddressTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.HasIndex("UserAddressTypeId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserAddressType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("UserAddressTypes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidated")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserEmailTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidationToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.HasIndex("UserEmailTypeId");

                    b.ToTable("UserEmails");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserEmailType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("UserEmailTypes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateVerifiedApproved")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerifiedApproved")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserLinkTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VerifiedApprovedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.HasIndex("UserLinkTypeId");

                    b.HasIndex("VerifiedApprovedByAppUserId");

                    b.ToTable("UserLinks");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserLinkType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("UserLinkTypes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageSubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserMessageTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.HasIndex("UserMessageTypeId");

                    b.ToTable("UserMessages");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserMessageTo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateLastRead")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastReadCount")
                        .HasColumnType("int");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("ToAppUserId");

                    b.ToTable("UserMessageTos");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserMessageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("UserMessageTypes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ItemRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoteBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteSubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentNoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserNoteTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("ParentNoteId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.HasIndex("UserNoteTypeId");

                    b.ToTable("UserNotes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserNoteType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("UserNoteTypes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCellular")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserPhoneTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidationToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.HasIndex("UserPhoneTypeId");

                    b.ToTable("UserPhones");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserPhoneType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("UserPhoneTypes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.Organization", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationAddress", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.OrganizationAddressType", "OrganizationAddressType")
                        .WithMany("OrganizationAddresses")
                        .HasForeignKey("OrganizationAddressTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.Organization", "Organization")
                        .WithMany("OrganizationAddresses")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("Organization");

                    b.Navigation("OrganizationAddressType");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationAddressType", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationEmail", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.OrganizationEmailType", "OrganizationEmailType")
                        .WithMany("OrganizationEmails")
                        .HasForeignKey("OrganizationEmailTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.Organization", "Organization")
                        .WithMany("OrganizationEmails")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("Organization");

                    b.Navigation("OrganizationEmailType");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationEmailType", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationLink", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.Organization", "Organization")
                        .WithMany("OrganizationLinks")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.OrganizationLinkType", "OrganizationLinkType")
                        .WithMany("OrganizationLinks")
                        .HasForeignKey("OrganizationLinkTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ben.Data.Source.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("VerifiedApprovedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("Organization");

                    b.Navigation("OrganizationLinkType");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationLinkType", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationNote", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.Organization", "Organization")
                        .WithMany("OrganizationNotes")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.OrganizationNoteType", "OrganizationNoteType")
                        .WithMany("OrganizationNotes")
                        .HasForeignKey("OrganizationNoteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.OrganizationNote", "ParentNote")
                        .WithMany("ChildNotes")
                        .HasForeignKey("ParentNoteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("Organization");

                    b.Navigation("OrganizationNoteType");

                    b.Navigation("ParentNote");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationNoteType", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationPage", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.Organization", "Organization")
                        .WithMany("OrganizationPages")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("Organization");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationPhone", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.Organization", "Organization")
                        .WithMany("OrganizationPhones")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.OrganizationPhoneType", "OrganizationPhoneType")
                        .WithMany("OrganizationPhones")
                        .HasForeignKey("OrganizationPhoneTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("Organization");

                    b.Navigation("OrganizationPhoneType");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationPhoneType", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserAddress", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "AppUser")
                        .WithMany("UserAddresses")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ben.Data.Source.Entities.UserAddressType", "UserAddressType")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserAddressTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");

                    b.Navigation("UserAddressType");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserAddressType", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserEmail", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "AppUser")
                        .WithMany("UserEmails")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ben.Data.Source.Entities.UserEmailType", "UserEmailType")
                        .WithMany("UserEmails")
                        .HasForeignKey("UserEmailTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");

                    b.Navigation("UserEmailType");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserEmailType", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserLink", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "AppUser")
                        .WithMany("UserLinks")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ben.Data.Source.Entities.UserLinkType", "UserLinkType")
                        .WithMany("UserLinks")
                        .HasForeignKey("UserLinkTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("VerifiedApprovedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AppUser");

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");

                    b.Navigation("UserLinkType");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserLinkType", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserMessage", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany("CreatedMessages")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.UserMessage", null)
                        .WithMany()
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ben.Data.Source.Entities.UserMessageType", "UserMessageType")
                        .WithMany("UserMessages")
                        .HasForeignKey("UserMessageTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");

                    b.Navigation("UserMessageType");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserMessageTo", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.UserMessage", "UserMessage")
                        .WithMany("UserMessageTos")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "ToAppUser")
                        .WithMany("ReceivedUserMessageTos")
                        .HasForeignKey("ToAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ToAppUser");

                    b.Navigation("UserMessage");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserMessageType", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserNote", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany("CreatedUserNotes")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.UserNote", null)
                        .WithMany()
                        .HasForeignKey("ParentNoteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ben.Data.Source.Entities.UserNoteType", "UserNoteType")
                        .WithMany("UserNotes")
                        .HasForeignKey("UserNoteTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");

                    b.Navigation("UserNoteType");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserNoteType", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserPhone", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "AppUser")
                        .WithMany("UserPhones")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ben.Data.Source.Entities.UserPhoneType", "UserPhoneType")
                        .WithMany("UserPhones")
                        .HasForeignKey("UserPhoneTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");

                    b.Navigation("UserPhoneType");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserPhoneType", b =>
                {
                    b.HasOne("Ben.Data.Source.Entities.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ben.Data.Source.Entities.AppUser", "UpdatedByAppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("UpdatedByAppUser");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.AppUser", b =>
                {
                    b.Navigation("CreatedMessages");

                    b.Navigation("CreatedUserNotes");

                    b.Navigation("ReceivedUserMessageTos");

                    b.Navigation("UserAddresses");

                    b.Navigation("UserEmails");

                    b.Navigation("UserLinks");

                    b.Navigation("UserPhones");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.Organization", b =>
                {
                    b.Navigation("OrganizationAddresses");

                    b.Navigation("OrganizationEmails");

                    b.Navigation("OrganizationLinks");

                    b.Navigation("OrganizationNotes");

                    b.Navigation("OrganizationPages");

                    b.Navigation("OrganizationPhones");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationAddressType", b =>
                {
                    b.Navigation("OrganizationAddresses");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationEmailType", b =>
                {
                    b.Navigation("OrganizationEmails");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationLinkType", b =>
                {
                    b.Navigation("OrganizationLinks");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationNote", b =>
                {
                    b.Navigation("ChildNotes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationNoteType", b =>
                {
                    b.Navigation("OrganizationNotes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.OrganizationPhoneType", b =>
                {
                    b.Navigation("OrganizationPhones");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserAddressType", b =>
                {
                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserEmailType", b =>
                {
                    b.Navigation("UserEmails");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserLinkType", b =>
                {
                    b.Navigation("UserLinks");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserMessage", b =>
                {
                    b.Navigation("UserMessageTos");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserMessageType", b =>
                {
                    b.Navigation("UserMessages");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserNoteType", b =>
                {
                    b.Navigation("UserNotes");
                });

            modelBuilder.Entity("Ben.Data.Source.Entities.UserPhoneType", b =>
                {
                    b.Navigation("UserPhones");
                });
#pragma warning restore 612, 618
        }
    }
}
